// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DataEdit$ReactHooksTemplate = require("./DataEdit.js");
var DataEntry$ReactHooksTemplate = require("./DataEntry.js");
var DataTable$ReactHooksTemplate = require("./DataTable.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Data entry"), React.createElement(DataEntry$ReactHooksTemplate.make, { }), React.createElement("h2", undefined, "Data table"), React.createElement(DataTable$ReactHooksTemplate.make, { }), React.createElement("h2", undefined, "Data edit"), React.createElement(DataEdit$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
