// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Store1$ReactHooksTemplate = require("./Store1.js");

function eventToValue($$event) {
  return $$event.target.value;
}

function DataEntry(Props) {
  var state = Curry._2(Store1$ReactHooksTemplate.api[/* useStore */5], undefined, /* () */0);
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setAddress = match$1[1];
  var address = match$1[0];
  var match$2 = React.useState((function () {
          return "";
        }));
  var setPhone = match$2[1];
  var phone = match$2[0];
  return React.createElement("div", undefined, React.createElement("form", undefined, React.createElement("label", undefined, "Name: "), React.createElement("input", {
                      key: "data-entry-name",
                      placeholder: "Company name",
                      type: "text",
                      value: name,
                      onChange: (function (ev) {
                          ev.persist();
                          return Curry._1(setName, (function (param) {
                                        return ev.target.value;
                                      }));
                        })
                    }), React.createElement("label", undefined, "Address: "), React.createElement("input", {
                      key: "data-entry-address",
                      placeholder: "Company address",
                      type: "text",
                      value: address,
                      onChange: (function (ev) {
                          ev.persist();
                          return Curry._1(setAddress, (function (param) {
                                        return ev.target.value;
                                      }));
                        })
                    }), React.createElement("label", undefined, "Phone: "), React.createElement("input", {
                      key: "data-entry-phone",
                      placeholder: "Company phone number",
                      type: "text",
                      value: phone,
                      onChange: (function (ev) {
                          ev.persist();
                          return Curry._1(setPhone, (function (param) {
                                        return ev.target.value;
                                      }));
                        })
                    })), React.createElement("button", {
                  onClick: (function (param) {
                      Curry._1(Store1$ReactHooksTemplate.api[/* dispatch */4], /* AddCompany */Block.__(0, [/* record */[
                                /* id */state[/* companies */0].length,
                                /* name */name,
                                /* address */address,
                                /* phone */phone
                              ]]));
                      Curry._1(setName, (function (param) {
                              return "";
                            }));
                      Curry._1(setAddress, (function (param) {
                              return "";
                            }));
                      return Curry._1(setPhone, (function (param) {
                                    return "";
                                  }));
                    })
                }, "Add company"));
}

var make = DataEntry;

exports.eventToValue = eventToValue;
exports.make = make;
/* react Not a pure module */
