// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Store1$ReactHooksTemplate = require("./Store1.js");

function eventToValue($$event) {
  return $$event.target.value;
}

function DataEdit(Props) {
  var globalState = Curry._2(Store1$ReactHooksTemplate.api[/* useStore */5], undefined, /* () */0);
  var match = React.useReducer((function (_state, action) {
          return action[0];
        }), /* record */[
        /* name */"",
        /* phone */"",
        /* address */""
      ]);
  var localDispatch = match[1];
  var localState = match[0];
  React.useEffect((function () {
          var match = globalState[/* editCompany */1];
          if (match !== undefined) {
            var company = match;
            Curry._1(localDispatch, /* UpdateLocalState */[/* record */[
                    /* name */company[/* name */1],
                    /* phone */company[/* phone */3],
                    /* address */company[/* address */2]
                  ]]);
          }
          return ;
        }), /* array */[globalState[/* editCompany */1]]);
  var match$1 = globalState[/* editCompany */1];
  if (match$1 !== undefined) {
    var company = match$1;
    return React.createElement("div", undefined, React.createElement("form", undefined, React.createElement("label", undefined, "Name: "), React.createElement("input", {
                        key: "data-entry-name",
                        placeholder: "Company name",
                        type: "text",
                        value: localState[/* name */0],
                        onChange: (function (ev) {
                            ev.persist();
                            var name = ev.target.value;
                            return Curry._1(localDispatch, /* UpdateLocalState */[/* record */[
                                          /* name */name,
                                          /* phone */localState[/* phone */1],
                                          /* address */localState[/* address */2]
                                        ]]);
                          })
                      }), React.createElement("label", undefined, "Address: "), React.createElement("input", {
                        key: "data-entry-address",
                        placeholder: "Company address",
                        type: "text",
                        value: localState[/* address */2],
                        onChange: (function (ev) {
                            ev.persist();
                            var address = ev.target.value;
                            return Curry._1(localDispatch, /* UpdateLocalState */[/* record */[
                                          /* name */localState[/* name */0],
                                          /* phone */localState[/* phone */1],
                                          /* address */address
                                        ]]);
                          })
                      }), React.createElement("label", undefined, "Phone: "), React.createElement("input", {
                        key: "data-entry-phone",
                        placeholder: "Company phone number",
                        type: "text",
                        value: localState[/* phone */1],
                        onChange: (function (ev) {
                            ev.persist();
                            var phone = ev.target.value;
                            return Curry._1(localDispatch, /* UpdateLocalState */[/* record */[
                                          /* name */localState[/* name */0],
                                          /* phone */phone,
                                          /* address */localState[/* address */2]
                                        ]]);
                          })
                      })), React.createElement("button", {
                    onClick: (function (ev) {
                        ev.persist();
                        Curry._1(Store1$ReactHooksTemplate.api[/* dispatch */4], /* UpdateCompany */Block.__(2, [/* record */[
                                  /* id */company[/* id */0],
                                  /* name */localState[/* name */0],
                                  /* address */localState[/* address */2],
                                  /* phone */localState[/* phone */1]
                                ]]));
                        return Curry._1(Store1$ReactHooksTemplate.api[/* dispatch */4], /* EditCompany */Block.__(3, [undefined]));
                      })
                  }, "Update company"), React.createElement("button", {
                    onClick: (function (ev) {
                        ev.persist();
                        return Curry._1(Store1$ReactHooksTemplate.api[/* dispatch */4], /* EditCompany */Block.__(3, [undefined]));
                      })
                  }, "Cancel"));
  } else {
    return React.createElement("div", undefined, "not editing at the moment");
  }
}

var make = DataEdit;

exports.eventToValue = eventToValue;
exports.make = make;
/* react Not a pure module */
